language: node_js
node_js:
  - 7
deploy:
  provider: heroku
  api_key:
    secure: SnAXVcm9K7aFCf0k55Jt73HBb740PLQh7QxcrDOhtPWXy87/cmIbc01V3aliiWcmS/qXrGT3mY/ZrmfUpKS06b+lMZhiVddMGHoJ9bWUZx46pTgEuKhuapFt7X8PYVYt1ErXP3gpN6mm66tLeaEaD4zkeP6lQzez0Ze44AeH1m7J6eu3mZa4ZP6pfsYvBXtHZad+7pogP3fuIhnI1Co8MZ0x3J9wyThnoBg8gCEiuLvmdORasB9ohPDEhGFzJj99OKncOYv6xO6MX3zxxdIT3XnESZ0ejGr+HX90fC5AYqikDC5W21Es3OQG21tL2KPXtexkixosnOCQNZbU3q0zHk540csGe2XX+vw0BkkuZgmYjcP00dPZ4TqPDpbtF41OySWr6kq4tDpfxhIqQGSzyMXRgTFvrXeBW0a6GDSpHrxfwV1nWSe8RdIMT2Fy4ZD9Ckkx5abp+FWTDvv4QmvGBAE+6pcaF8lcdUui4sO4wQlR2xrrojRB+G6pOjlFymRKW6x1b8+EZMqJzzmzNHJQWhKGB3vRDb5JomBBARsopRMVazoyiCV9UHz/xBLFk39THMLOgTzWSd0OC/83xAJtdtQeE1WlILeOWQgMIutvs18PLnLwldQuUIde7itasLVrxxWnOKIKN9mnDViiMyhytSIGG4I8v7zWSRrrlJzAxX4=
  app: dashboard-epitech-2019
