version: '3'
services:
  server:
    container_name: 'dashboard_app'
    build: ./app
    ports:
      - '8080:8080'
    environment:
      - REACT_APP_API_HOST=api
      - PORT=8080
  db:
    container_name: 'dashboard_db'
    image: 'mongo'
    volumes:
      - db-data:/data/db
    ports:
      - '27017-27019:27017-27019'
  api:
    container_name: 'dashboard_api'
    build: ./server
    environment:
      - DB_HOST=db
      - JWT_KEY='dashboard'
      - PORT=3000
    ports:
      - '3000:3000'
volumes:
  db-data: